server:
  port: 8201
  tomcat: 
    uri-encoding: utf-8   

spring:
  profiles:
    active: dev
  application:
    name: system
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    initialize: true
#    initialSize: 10
#    minIdle: 10
#    maxActive: 100
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
##    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxPoolPreparedStatementPerConnectionSize: 20
#    type: com.alibaba.druid.pool.DruidDataSource
##  jackson:
##    time-zone: GMT+8
##    date-format: yyyy-MM-dd HH:mm:ss
#
#mybatis:
#  config-location: classpath:mybatis-config.xml
#  mapper-locations: classpath*:/mapper/*.xml
#  type-aliases-package: com.yhyt.health.model
#
#
#logging:
#  file: /root/health/system.log
#  level:
#    org.springframework: debug
#
#
#alipay:
#  APPID: 2017101109249326
##  PARTNER: 2088511511698621
#  PARTNER: 2088821323908671
#  PRIVATEKEY: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBANpRcW5dHbjzo+SunaAP/shR6AsOk5NI/VlRdQVYQgJNWsKYgpHdcvXq5ZnmvhvFL+RU7bLOHYD2lHDqZq+HtQplmM2Xz+8t7ZuNR+5SfoWWo/yFwWppP8u/h5g2k51zF82mk5M8fOzinE4H952LtAWJ0gUGRKHmiq4DhvgxDul1AgMBAAECgYEAhXLbH1cT4AYt3I9QEpM0bkaCzJ9wXctz8bD1EvtL/hRCskh/J6JxrxiSmGyPMHJsP+oaEf4j0rznJ85gTlNpuXuKgOZnpsSCmMCSSeTmidx8vwEBblG/UN7IfKS9iDPbwMp5z4z9syycaMIv4N5+NuoGg9JN77uAkMOlHCs3MgECQQD89ysYYJSFAz0n/ITEM+IL5P2YNqb4vCO4QSYfUbhZY0QkHWOo34rsnRlgthlMHsAsOxGdNfCJOe77FcdQjkaVAkEA3O/gTNHCT7JUWvK/raCcUHLm6hAY7EX8I295zXj5ab0yykyB5I+AamhH6QWhtK/YmWURdzUSy94gRKdH1Em/YQJAHqTGeK6Cb1aEGwrw/l+Wm4BC5CSCt5D69sAVoSeiIFnxEDrrLrLdvmoNf/SvPdRfzTvel1/IYqc89vedbHm/vQJABFopVfoP1NgTd1Mu2XG/goow6E124DikteH9SUHnz+BtPrTxHhqBkhcJy5pTzCZmoubtyCZgf2mZwyB0dscZIQJBAN+89uUq2ctgpZtiqqyRL+6z3ma3e/oUcqsVSUYnN7JOyj8zaO+51NzY6PsR6OStujHVZ6TQq5X6ScZhspxtY1k=
#  SIGNTYPE: RSA
#  PUBLICKEY: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDaUXFuXR2486Pkrp2gD/7IUegLDpOTSP1ZUXUFWEICTVrCmIKR3XL16uWZ5r4bxS/kVO2yzh2A9pRw6mavh7UKZZjNl8/vLe2bjUfuUn6FlqP8hcFqaT/Lv4eYNpOdcxfNppOTPHzs4pxOB/edi7QFidIFBkSh5oquA4b4MQ7pdQIDAQAB
#  ALIPAY_PUBLICKEY: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDDI6d306Q8fIfCOaTXyiUeJHkrIvYISRcc73s3vF1ZT7XN8RNPwJxo8pWaJMmvyTn9N4HQ632qJBVHf8sxHi/fEsraprwCtzvzQETrNRwVxLO5jVmRGi60j8Ue1efIlzPXV9je9mkjzOmdssymZkh2QhUrCmZYI/FCEa3/cNMW0QIDAQAB
#  NOTIFYURL: http://apitest.cis95132.com:8800/order/alipay/notify
#
#weixinpay:
#  APPID: wxdb479b4baf251e33
##  MCHID: 1480131802
#  MCHID: 1490482872
#  NOTIFYURL: http://apitest.cis95132.com:8800/order/weixinpay/notify
#  ENCODINGAESKEY: mQmZ9XMkC1x0qDiwvXnStxDWoC99J5rB

quartz:
  scheduler:
    instanceName: yhytSchedule
#org:
#  quartz:
#    dataSource:
#      myDS:
#        driver: