
spring:
  datasource:
    username: root
    password: xjk1234
    url: jdbc:mysql://172.30.0.230:3306/xjk?useUnicode=true&characterEncoding=utf-8
  redis:
      host: 172.30.0.219
      port: 6379
      password: 123456

eureka: 
  client:
    service-url:
      defaultZone: http://172.30.0.219:8000/eureka/,http://172.30.0.233:8000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30

url:
  patientUrl: http://patient/
  systemUrl: http://system/
  dialogUrl: http://dialog/
  gateWay: https://test.cis95132.com:8000/

